---
title: "K-Means Clustering"
author: "Amran A"
output: html_document
---
 

#Introduction
#The objective of this project in R is to perform clustering analysis on protein consumption data for different European countries. The visualization and clustering analysis in this project provide valuable insights into European protein consumption patterns across different geographic regions and protein sources. By clustering the data based on similarities, distinct clusters are represented by different colors. One plot focuses on red and white meat consumption, revealing similarities in consumption patterns among European countries. Overall, these findings contribute to our understanding of European protein consumption by highlighting similarities and differences among regions and protein sources.



#Importing datasets
```{r echo=FALSE}
 #loading packages
library(tidyverse)
install.packages(cluster)
library(cluster)
install.packages(factoextra)
library(factoextra)

# Importing the data sets
protein <- read.csv("protein.csv", header=TRUE, row.names=1) 
head(protein, 10)

# using the scale function to center the variables and make them comparable
protein_scaled <- scale(protein, center=TRUE, scale=TRUE)


#Clustering red and white meat: The variables "RedMeat" and "WhiteMeat" are extracted from the scaled data. The k-means clustering algorithm is applied to these variables with k=3 (3 clusters). The resulting clusters are plotted on a scatter plot of red meat against white meat.
red_white = protein_scaled[,c("WhiteMeat","RedMeat")]
head(red_white)
plot(red_white)

# Used k-means to make 3 clusters
cluster_redwhite <- kmeans(red_white, centers=3)

# Plotting with the labels
plot(red_white, xlim=c(-2,2.75), 
     type="n", xlab="Red Meat", ylab="White Meat")  
text(red_white, labels=rownames(red_white), 
     col=rainbow(3)[cluster_redwhite$cluster])



#Clustering all nine protein groups: The k-means clustering algorithm is applied to all nine protein groups in the scaled data with k=7 (7 clusters). The resulting clusters are analyzed and visualized on scatter plots of various protein variables (red meat vs white meat, milk vs eggs, milk vs cereals).
cluster_all <- kmeans(protein_scaled, centers=7, nstart=30)
names(cluster_all)

# Extract some of the information from the fitted model
cluster_all$centers
cluster_all$cluster



# Resulting clusters (coloured) are on a scatter plot of white meat against red meat.
  # Plotting the clustering on the red-white meat axes
plot(protein_scaled[,"WhiteMeat"], protein_scaled[,"RedMeat"], xlim=c(-2,2.75), 
     type="n", ylab="Red Meat", xlab="White Meat")
text(protein_scaled[,"WhiteMeat"], protein_scaled[,"RedMeat"], labels=rownames(protein), 
     col=rainbow(7)[cluster_all$cluster]) 

# Plotting milk vs Eggs variables
plot(protein_scaled[,"Eggs"], protein_scaled[,"Milk"], xlim=c(-2,2.75), 
     type="n", xlab="Eggs", ylab="Milk")
text(protein_scaled[,"Eggs"], protein_scaled[,"Milk"], labels=rownames(protein), 
     col=rainbow(7)[cluster_all$cluster]) 

# Plotting Milk vs Cereals variables
plot(protein_scaled[,"Cereals"], protein_scaled[,"Milk"], xlim=c(-2,2.75), 
     type="n", xlab="Cereals", ylab="Milk")
text(protein_scaled[,"Cereals"], protein_scaled[,"Milk"], labels=rownames(protein), 
     col=rainbow(7)[cluster_all$cluster])

#clustering  Milk and Cereal  (p=2) and using 3 clusters (k=3)
  # Milk and Cereal variables
milk_cereals = protein_scaled[,c("Milk","Cereals")]
head(milk_cereals)
plot(milk_cereals)

# Used k-means to make 3 clusters
cluster_milkcereals <- kmeans(milk_cereals, centers=3)


## Results analysis
#The visualization results for all of these show European protein consumption for different sources of proteins in different geographic regions. The data is clustered based on similarities, and the resulting clusters are represented by different colors. In my results, one of the plots demonstrates the consumption of red and white meat in different European countries. The countries are clustered together based on their protein (red and white meat) consumption values, revealing similarities in consumption patterns among them, for example, countries like Germany, Austria, and Ireland have a high consumption of Red Meat, and countries such as the United Kingdom and France have a high consumption of White Meat. Another one of the plot's examines the consumption of milk and eggs in European countries, which is clustered based on similarities in the resulting values for consumption, for example, countries such as portugal and Romania have a low consumption of both Milk and Eggs, whereas countries such as the United Kingdom and Ireland have a high consumption of both milk and Eggs. Additionally, I included a plot that visualizes milk vs cereal protein consumption in Europe, clustering the regions based on their similarities in consumption amounts, for this plot we have countries such as Finland with a high consumption of milk but a low consumption of cereal, whereas we also have countries such as Bulgaria with a high consumption of cereal but a low consumption of milk.

#In summary, the visualization and clustering analysis provide insights into European protein consumption patterns for various protein sources. The clusters allow us to identify groups of countries with similar consumption behaviors, contributing to our understanding of protein consumption across different regions.  
  
  #Fixing PDF knitting issue with this package
install.packages("tinytex")
tinytex::install_tinytex()


```



